on:
  workflow_dispatch:
  push:
    branches:
      - "main"

name: Build Dev

env:
  FLUTTER_VERSION: 3.16.0

jobs:
  build_release:
    name: Build dev version
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: android
            runner: ubuntu-latest
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Setup Java
        if: matrix.os == 'android'
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "11"

      - name: Build release APK
        run: |
          flutter build apk --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release-dev
          path: |
            app-release.apk